# Generated by Django 4.2.10 on 2025-08-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnaVeri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alan_1', models.CharField(max_length=255, verbose_name='Alan 1')),
                ('alan_2', models.CharField(max_length=255, verbose_name='Alan 2')),
                ('alan_3', models.CharField(max_length=255, verbose_name='Alan 3')),
                ('alan_4', models.CharField(max_length=255, verbose_name='Alan 4')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('guncellenme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Ana Veri',
                'verbose_name_plural': 'Ana Veriler',
                'ordering': ['-olusturulma_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='SutunAyarlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sutun_1_baslik', models.CharField(default='Sütun 1', max_length=50, verbose_name='1. Sütun Başlığı')),
                ('sutun_2_baslik', models.CharField(default='Sütun 2', max_length=50, verbose_name='2. Sütun Başlığı')),
                ('sutun_3_baslik', models.CharField(default='Sütun 3', max_length=50, verbose_name='3. Sütun Başlığı')),
                ('sutun_4_baslik', models.CharField(default='Sütun 4', max_length=50, verbose_name='4. Sütun Başlığı')),
                ('guncellenme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Sütun Ayarları',
                'verbose_name_plural': 'Sütun Ayarları',
            },
        ),
    ]
