# Generated by Django 4.2.10 on 2025-08-25 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veri_yonetimi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sütun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100, verbose_name='Sütun Adı')),
                ('sıra', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('oluşturulma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
            ],
            options={
                'verbose_name': 'Sütun',
                'verbose_name_plural': 'Sütunlar',
                'ordering': ['sıra', 'ad'],
            },
        ),
        migrations.AlterModelOptions(
            name='sutunayarlari',
            options={'verbose_name': 'Sütun Ayarları (Eski)', 'verbose_name_plural': 'Sütun Ayarları (Eski)'},
        ),
        migrations.RemoveField(
            model_name='anaveri',
            name='alan_1',
        ),
        migrations.RemoveField(
            model_name='anaveri',
            name='alan_2',
        ),
        migrations.RemoveField(
            model_name='anaveri',
            name='alan_3',
        ),
        migrations.RemoveField(
            model_name='anaveri',
            name='alan_4',
        ),
        migrations.CreateModel(
            name='VeriDeger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deger', models.CharField(max_length=500, verbose_name='Değer')),
                ('ana_veri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='degerler', to='veri_yonetimi.anaveri', verbose_name='Ana Veri')),
                ('sutun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veri_yonetimi.sütun', verbose_name='Sütun')),
            ],
            options={
                'verbose_name': 'Veri Değeri',
                'verbose_name_plural': 'Veri Değerleri',
                'unique_together': {('ana_veri', 'sutun')},
            },
        ),
    ]
