# Generated by Django 5.2.5 on 2025-08-26 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veri_yonetimi', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='anaveri',
            name='kurulacak_cihaz_sayisi',
            field=models.PositiveIntegerField(default=0, help_text='Bu il için kurulacak toplam cihaz sayısı', verbose_name='Kurulacak Cihaz Sayısı'),
        ),
        migrations.AddField(
            model_name='anaveri',
            name='kurulan_cihaz_sayisi',
            field=models.PositiveIntegerField(default=0, help_text='Bu il için şu ana kadar kurulan cihaz sayısı', verbose_name='Kurulan Cihaz Sayısı'),
        ),
    ]
