# Generated by Django 5.2.5 on 2025-08-26 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veri_yonetimi', '0004_anaveri_kurulacak_cihaz_sayisi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anaveri',
            name='arizali_cihaz_sayisi',
            field=models.PositiveIntegerField(default=0, help_text='Bu il için arızalı olan cihaz sayısı', verbose_name='Arızalı Cihaz Sayısı'),
        ),
    ]
