# Generated by Django 4.2.10 on 2025-08-26 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veri_yonetimi', '0005_anaveri_arizali_cihaz_sayisi'),
    ]

    operations = [
        migrations.AddField(
            model_name='sütun',
            name='tip',
            field=models.CharField(choices=[('dinamik', 'Dinamik Sütun'), ('kurulacak', 'Kurulacak Cihaz Sayısı'), ('kurulan', 'Kurulan Cihaz Sayısı'), ('arizali', 'Arızalı Cihaz Sayısı'), ('tamamlanma', 'Tamamlanma Durumu')], default='dinamik', max_length=20, verbose_name='Sütun Tipi'),
        ),
    ]
