# Generated by Django 4.2.10 on 2025-08-26 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veri_yonetimi', '0006_sütun_tip'),
    ]

    operations = [
        migrations.AddField(
            model_name='anaveri',
            name='il_adi',
            field=models.CharField(default='İstanbul', max_length=100, verbose_name='İl Adı'),
        ),
    ]
