# Generated by Django 5.2.5 on 2025-08-27 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veri_yonetimi', '0007_anaveri_il_adi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sütun',
            options={'ordering': ['menu_tipi', 'sıra', 'ad'], 'verbose_name': 'Sütun', 'verbose_name_plural': 'Sütunlar'},
        ),
        migrations.AddField(
            model_name='sütun',
            name='genislik',
            field=models.CharField(default='auto', help_text='CSS genişlik değeri (px, %, auto)', max_length=20, verbose_name='Genişlik'),
        ),
        migrations.AddField(
            model_name='sütun',
            name='gorunur',
            field=models.BooleanField(default=True, verbose_name='Görünür'),
        ),
        migrations.AddField(
            model_name='sütun',
            name='hizalama',
            field=models.CharField(choices=[('left', 'Sol'), ('center', 'Orta'), ('right', 'Sağ')], default='left', max_length=20, verbose_name='Hizalama'),
        ),
        migrations.AddField(
            model_name='sütun',
            name='menu_tipi',
            field=models.CharField(choices=[('veri_listesi', 'Veri Listesi'), ('cihaz_turleri', 'Cihaz Türleri'), ('illere_gore_cihaz_turleri', 'İllere Göre Cihaz Türleri'), ('genel', 'Genel (Tüm Menüler)')], default='genel', max_length=30, verbose_name='Menü Tipi'),
        ),
        migrations.AlterField(
            model_name='sütun',
            name='tip',
            field=models.CharField(choices=[('dinamik', 'Dinamik Sütun'), ('kurulacak', 'Kurulacak Cihaz Sayısı'), ('kurulan', 'Kurulan Cihaz Sayısı'), ('arizali', 'Arızalı Cihaz Sayısı'), ('tamamlanma', 'Tamamlanma Durumu'), ('veri_listesi', 'Veri Listesi Sütunu'), ('cihaz_turleri', 'Cihaz Türleri Sütunu'), ('illere_gore', 'İllere Göre Cihaz Türleri Sütunu')], default='dinamik', max_length=20, verbose_name='Sütun Tipi'),
        ),
    ]
