# Generated by Django 5.2.5 on 2025-08-28 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veri_yonetimi', '0008_alter_sütun_options_sütun_genislik_sütun_gorunur_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='sütun',
            name='menu_tipi',
            field=models.CharField(choices=[('veri_listesi', 'Veri Listesi'), ('cihaz_turleri', 'Cihaz Türleri'), ('genel', 'Genel (Tüm Menüler)')], default='genel', max_length=30, verbose_name='Menü Tipi'),
        ),
        migrations.AlterField(
            model_name='sütun',
            name='tip',
            field=models.CharField(choices=[('dinamik', 'Dinamik Sütun'), ('kurulacak', 'Kurulacak Cihaz Sayısı'), ('kurulan', 'Kurulan Cihaz Sayısı'), ('arizali', 'Arızalı Cihaz Sayısı'), ('tamamlanma', 'Tamamlanma Durumu'), ('veri_listesi', 'Veri Listesi Sütunu'), ('cihaz_turleri', 'Cihaz Türleri Sütunu')], default='dinamik', max_length=20, verbose_name='Sütun Tipi'),
        ),
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('islem_tipi', models.CharField(choices=[('kullanici_olusturuldu', 'Kullanıcı Oluşturuldu'), ('kullanici_guncellendi', 'Kullanıcı Güncellendi'), ('kullanici_silindi', 'Kullanıcı Silindi'), ('durum_degistirildi', 'Durum Değiştirildi'), ('yetki_degistirildi', 'Yetki Değiştirildi'), ('giris_yapildi', 'Giriş Yapıldı'), ('cikis_yapildi', 'Çıkış Yapıldı'), ('profil_guncellendi', 'Profil Güncellendi'), ('sifre_degistirildi', 'Şifre Değiştirildi'), ('veri_eklendi', 'Veri Eklendi'), ('veri_guncellendi', 'Veri Güncellendi'), ('veri_silindi', 'Veri Silindi'), ('sutun_eklendi', 'Sütun Eklendi'), ('sutun_guncellendi', 'Sütun Güncellendi'), ('sutun_silindi', 'Sütun Silindi')], max_length=50, verbose_name='İşlem Tipi')),
                ('aciklama', models.TextField(verbose_name='Açıklama')),
                ('ip_adresi', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Adresi')),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True, verbose_name='User Agent')),
                ('eski_deger', models.JSONField(blank=True, null=True, verbose_name='Eski Değer')),
                ('yeni_deger', models.JSONField(blank=True, null=True, verbose_name='Yeni Değer')),
                ('tarih', models.DateTimeField(auto_now_add=True, verbose_name='Tarih')),
                ('islem_yapan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yapilan_islemler', to=settings.AUTH_USER_MODEL, verbose_name='İşlemi Yapan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_logs', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Kullanıcı İşlem Logu',
                'verbose_name_plural': 'Kullanıcı İşlem Logları',
                'ordering': ['-tarih'],
            },
        ),
    ]
