# Generated by Django 5.2.5 on 2025-08-28 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veri_yonetimi', '0009_alter_sütun_menu_tipi_alter_sütun_tip_userlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='sorumlu_il',
            field=models.CharField(blank=True, help_text='Bu kullanıcının sorumlu olduğu il. Boşsa tüm illeri görebilir.', max_length=100, null=True, verbose_name='Sorumlu İl'),
        ),
    ]
