# Generated by Django 5.2.5 on 2025-08-28 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veri_yonetimi', '0010_userprofile_sorumlu_il'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='sorumlu_il',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sorumlu_iller',
            field=models.TextField(blank=True, help_text='Bu kullanıcının sorumlu olduğu iller (virgülle ayrılmış). Boşsa tüm illeri görebilir.', null=True, verbose_name='Sorumlu İller'),
        ),
    ]
