# Generated by Django 5.2.5 on 2025-08-28 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veri_yonetimi', '0011_remove_userprofile_sorumlu_il_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(default='DVP', max_length=100, verbose_name='Uygulama Adı')),
                ('app_description', models.CharField(default='Dinamik Veri Paneli', max_length=200, verbose_name='Uygulama Açıklaması')),
                ('app_logo', models.FileField(blank=True, null=True, upload_to='logos/', verbose_name='Uygulama Logosu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Uygulama Ayarları',
                'verbose_name_plural': 'Uygulama Ayarları',
            },
        ),
    ]
