# Generated by Django 4.2.10 on 2025-09-06 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("veri_yonetimi", "0012_appsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("viewer", "Seyirci"),
                    ("province_manager", "İl Sorumlusu"),
                    ("province_admin", "İl Yöneticisi"),
                    ("super_user", "Süper Kullanıcı"),
                ],
                default="viewer",
                max_length=20,
                verbose_name="Kullanıcı Rolü",
            ),
        ),
    ]
