# Generated by Django 4.2.10 on 2025-09-06 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assistant", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="assistantsettings",
            options={
                "verbose_name": "Asistan Ayarı",
                "verbose_name_plural": "Asistan Ayarları",
            },
        ),
        migrations.AlterField(
            model_name="assistantsettings",
            name="name",
            field=models.CharField(default="AI Asistan", max_length=100),
        ),
    ]
